"""Tests for ACAT/security transfer handling in CostBasisCalculator (C3.3).

Verifies that transfer_in / transfer_out transactions are NON-REALIZING:
lots persist across the transfer, cost basis carries across brokers, and
realized P&L is not generated by the transfer itself.
"""
import pytest
import pandas as pd

pytestmark = pytest.mark.critical

from src.financial_analysis.cost_basis import CostBasisCalculator


class TestTransferNonRealizing:
    """CostBasisCalculator must treat ACAT transfers as non-realizing (C3.3)."""

    def test_transfer_non_realizing_lots_persist(self):
        """buy 10 @ 100, transfer_out 10, transfer_in 10 → lots persist, realized_pnl=0.

        The ACAT transfer_out and transfer_in are both non-realizing:
        - transfer_out does not sell the lots (no realized P&L)
        - transfer_in does not add new lots (no cost basis change)
        After the round-trip, position = 10, cost = 1000, realized_pnl = 0.
        """
        calc = CostBasisCalculator("US_STK_VOO")
        transactions = pd.DataFrame(
            {
                "transaction_type": ["buy", "transfer_out", "transfer_in"],
                "quantity": [10.0, 10.0, 10.0],
                "price_unit": [100.0, 0.0, 0.0],
                "amount_net": [-1000.0, 0.0, 0.0],
                "currency": ["USD", "USD", "USD"],
            },
            index=pd.DatetimeIndex(
                [
                    pd.Timestamp("2024-01-15"),
                    pd.Timestamp("2026-05-24"),
                    pd.Timestamp("2026-05-24"),
                ]
            ),
        )

        calc.process_transactions(transactions)

        assert calc.get_current_position() == 10.0, (
            f"Position should remain 10 after non-realizing transfer round-trip. "
            f"Got {calc.get_current_position()}"
        )
        assert abs(calc.get_total_cost_basis() - 1000.0) < 0.01, (
            f"Cost basis should remain 1000 after transfer (lots persist). "
            f"Got {calc.get_total_cost_basis()}"
        )
        assert calc.realized_pnl == 0.0, (
            f"Realized P&L should be 0 — transfers are non-realizing. "
            f"Got {calc.realized_pnl}"
        )

    def test_transfer_out_does_not_consume_lots(self):
        """transfer_out must NOT consume FIFO lots (it's non-realizing).

        If transfer_out were treated like a sell, it would consume the lots and
        a subsequent sell would find no lots → P&L calculation breaks.
        """
        calc = CostBasisCalculator("US_STK_VOO")
        transactions = pd.DataFrame(
            {
                "transaction_type": ["buy", "transfer_out", "sell"],
                "quantity": [10.0, 5.0, 5.0],
                "price_unit": [100.0, 0.0, 120.0],
                "amount_net": [-1000.0, 0.0, 600.0],
                "currency": ["USD", "USD", "USD"],
            },
            index=pd.DatetimeIndex(
                [
                    pd.Timestamp("2024-01-15"),
                    pd.Timestamp("2026-05-24"),
                    pd.Timestamp("2026-06-01"),
                ]
            ),
        )

        calc.process_transactions(transactions)

        # transfer_out of 5 is non-realizing (does not consume lots).
        # sell 5 at $120 proceeds: cost = $100*5 = $500 → realized = $600-$500 = $100.
        # position = 10 - 5 sell = 5 remaining (transfer_out did not reduce lot count)
        assert calc.get_current_position() == 5.0, (
            f"Only the sell should consume lots. Got {calc.get_current_position()}"
        )
        assert abs(calc.get_total_cost_basis() - 500.0) < 0.01, (
            f"Remaining cost = 5 @ $100 = $500. Got {calc.get_total_cost_basis()}"
        )
        assert abs(calc.realized_pnl - 100.0) < 0.01, (
            f"Realized P&L from sell: $600 - $500 = $100. Got {calc.realized_pnl}"
        )

    def test_transfer_in_does_not_add_lots(self):
        """transfer_in must NOT add new FIFO lots (it's non-realizing, zero cost basis).

        If transfer_in were treated like a buy at qty=21, price=0, it would add a $0-cost
        lot and inflate position while diluting average cost.
        """
        calc = CostBasisCalculator("US_STK_VOO")
        transactions = pd.DataFrame(
            {
                "transaction_type": ["buy", "transfer_in"],
                "quantity": [10.0, 10.0],
                "price_unit": [100.0, 0.0],
                "amount_net": [-1000.0, 0.0],
                "currency": ["USD", "USD"],
            },
            index=pd.DatetimeIndex(
                [
                    pd.Timestamp("2024-01-15"),
                    pd.Timestamp("2026-05-24"),
                ]
            ),
        )

        calc.process_transactions(transactions)

        # transfer_in is non-realizing → position stays 10 (the original buy lots),
        # NOT 20. Cost basis stays 1000, not diluted to $50/share by a $0-cost lot.
        assert calc.get_current_position() == 10.0, (
            f"transfer_in must not add new lots. Got {calc.get_current_position()}"
        )
        assert abs(calc.get_total_cost_basis() - 1000.0) < 0.01, (
            f"Cost basis must not be affected by transfer_in. "
            f"Got {calc.get_total_cost_basis()}"
        )

    def test_merged_ledger_voo_scenario(self):
        """Full merged VOO scenario: buy 27 → sell 6 → other(transfer-out) -21 → transfer_in 21.

        This is the critical C3.3 scenario. When both brokers' ledgers are merged
        (Schwab_CSV + Broker_IBKR), the FIFO calculator must:
          1. Add lot: 27 @ ~599 (Schwab buy)
          2. Consume 6 shares FIFO (Schwab sell) → 21 remaining @ $599
          3. 'other' -21 → falls through (not a known type → no-op; same as transfer)
          4. transfer_in 21 → non-realizing no-op
          5. Remaining position = 21, cost ≈ 16173.81 * (21/27) ≈ 12579 → per unit ≈ 599

        The acceptance gate: get_current_position() = 21, cost_per_unit ≈ 599.
        """
        calc = CostBasisCalculator("US_STK_VOO")
        transactions = pd.DataFrame(
            {
                "transaction_type": ["buy", "sell", "other", "transfer_in"],
                "quantity": [27.0, 6.0, 21.0, 21.0],
                "price_unit": [599.0, 610.0, 0.0, 0.0],
                "amount_net": [-16173.81, 3660.0, 0.0, 0.0],
                "currency": ["USD", "USD", "USD", "USD"],
            },
            index=pd.DatetimeIndex(
                [
                    pd.Timestamp("2024-01-15"),  # Schwab buy
                    pd.Timestamp("2025-03-10"),  # Schwab sell 6
                    pd.Timestamp("2026-05-24"),  # Schwab ACAT transfer-out (maps to 'other')
                    pd.Timestamp("2026-05-24"),  # IBKR transfer_in
                ]
            ),
        )

        calc.process_transactions(transactions)

        position = calc.get_current_position()
        total_cost = calc.get_total_cost_basis()
        cost_per_unit = calc.get_average_cost()

        assert position == 21.0, (
            f"After buy 27, sell 6, transfer_out 21 (no-op), transfer_in 21 (no-op), "
            f"position must be 21. Got {position}"
        )
        assert total_cost > 0, (
            f"Total cost must be > 0 after merged FIFO. Got {total_cost}"
        )
        assert 550 <= cost_per_unit <= 650, (
            f"Cost per unit should be approx $599 (buy price minus FIFO sell). "
            f"Got {cost_per_unit:.4f}. Expected range [550, 650]."
        )
        assert calc.realized_pnl > 0, (
            f"Realized P&L from sell-6 at $610 vs cost $599: should be positive. "
            f"Got {calc.realized_pnl}"
        )
